[package]
name = "kangarootwelve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turboshake = { version = "=0.1.4", features = ["dev"]}

[dev-dependencies]
hex = "0.4.3"
criterion = "0.4.0"
rand = "0.8.5"

[lib]
bench = false

[[bench]]
name = "kangarootwelve"
harness = false
