name: KangarooTwelve

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run single-threaded tests
      run: cargo test --lib
    - name: Run multi-threaded tests
      run: cargo test --lib --features multi_threaded
